#!/usr/bin/env python3
"""Requirement-to-test traceability matrix.

Reads the requirements table in docs/requirements.md and the
@pytest.mark.req("CL-nnn") markers in tests/test_*.py, writes
docs/traceability.md, and exits 1 if

  * a requirement whose "Verified by" cell contains "T:" has no tagged test, or
  * a test is tagged with an ID that is not in the requirements table.
"""
import argparse
import ast
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent


def parse_requirements(path):
    """Return [(id, text, verified_by)] from the markdown table."""
    rows = []
    for line in path.read_text().splitlines():
        if not line.startswith("| CL-"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 3:
            raise ValueError(f"expected 3 columns in: {line}")
        rows.append(tuple(cells))
    return rows


def needs_test(verified_by):
    return any(part.strip().startswith("T:") for part in verified_by.split(";"))


def find_tests(tests_dir):
    """Return {requirement id: sorted test names} from the req markers."""
    found = {}
    for path in sorted(tests_dir.glob("test_*.py")):
        tree = ast.parse(path.read_text(), filename=str(path))
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            if not node.name.startswith("test_"):
                continue
            for deco in node.decorator_list:
                if (isinstance(deco, ast.Call) and isinstance(deco.func, ast.Attribute)
                        and deco.func.attr == "req" and deco.args
                        and isinstance(deco.args[0], ast.Constant)
                        and isinstance(deco.args[0].value, str)):
                    found.setdefault(deco.args[0].value, set()).add(f"{path.name}::{node.name}")
    return {k: sorted(v) for k, v in found.items()}


def render(rows, tests):
    out = [
        "# Traceability matrix",
        "",
        "Generated by `tools/trace_matrix.py` from `docs/requirements.md` and the",
        "`@pytest.mark.req` markers in `tests/`. Do not edit by hand.",
        "",
        "| ID | Requirement | Verified by | Tests | Status |",
        "|---|---|---|---|---|",
    ]
    for rid, text, verified in rows:
        names = tests.get(rid, [])
        cell = "<br>".join(f"`{n}`" for n in names) if names else "-"
        if needs_test(verified):
            status = "covered" if names else "**MISSING TEST**"
        else:
            status = "CI / inspection" + (f" (+{len(names)} tests)" if names else "")
        out.append(f"| {rid} | {text} | {verified} | {cell} | {status} |")
    total = len(rows)
    covered = sum(1 for rid, _, v in rows if not needs_test(v) or tests.get(rid))
    out += ["", f"{covered} of {total} requirements covered.", ""]
    return "\n".join(out)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--requirements", type=pathlib.Path, default=ROOT / "docs" / "requirements.md")
    parser.add_argument("--tests", type=pathlib.Path, default=ROOT / "tests")
    parser.add_argument("--out", type=pathlib.Path, default=ROOT / "docs" / "traceability.md")
    args = parser.parse_args(argv)

    try:
        rows = parse_requirements(args.requirements)
        tests = find_tests(args.tests)
    except (OSError, ValueError, SyntaxError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if not rows:
        print(f"error: no requirements found in {args.requirements}", file=sys.stderr)
        return 2

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(rows, tests))

    known = {rid for rid, _, _ in rows}
    failed = False
    for rid, _, verified in rows:
        if needs_test(verified) and not tests.get(rid):
            print(f"FAIL: {rid} has no test (add @pytest.mark.req(\"{rid}\"))", file=sys.stderr)
            failed = True
    for rid in sorted(set(tests) - known):
        print(f"FAIL: tests are tagged {rid}, which is not in {args.requirements.name}", file=sys.stderr)
        failed = True
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
